### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by drak42** [jo3stevens/ACServerManager#1]
Hey,

Do you intend to release a linux version for the Linux stand alone server?

**Comment by jo3stevens** [comment]
Hey

I hadn't thought about it, but as it's Node it will run on Linux, it's probably just the file paths that need to be updated. I haven't got a Linux server running, but if I find some time I'll give it a go.


Cheers

**Comment by jo3stevens** [comment]
Hey @drak42 

Somebody was kind enough to add linux support if you're still looking for it
