### ISSUE TITLE
about stracker on linux

### ISSUE THREAD

**Issue by icoicqico** [jo3stevens/ACServerManager#10]
I can run stacker on linux, but not on the web page? Is the webpage stracker start function only support windows? I have tried to set stacker loaction as .../stracker or .../stracker/stracker_linux_x86 and doesn't work. Could anyone help me? Thanks a lot.

**Comment by icoicqico** [comment]
I have checked the server.js, controller.js, index.html, services.js. In server.js, stracker setting seems not support linux, if I activate the stracker( set the path @ settings.js), couldn't start the Stracker server and the ACservermanager will be no response too( cant connect to the port3000 page) if i disable the stacker, acservermanager work fine but without stracker. 

I have tried to modfiy the server.js about stracker, /api/stracker part?(sth like that) change the stracker to be ./stracker stracker_ini stracker.ini (the way to start stracker in linux), still the same ( the port 3000 would be no response after a few second, and Stracker not work too)

So I want to know, does the stracker function works fine in windows(I mean start at the webpage)? Because someone said it's working but the gui has some errors cause loading all the time but the server works. And when you start ACserver on the manager, ACserver status will be"loading", at the same time, Stracker status will be"loading too"(only click start for ACServer both status loading , and the Stacker's buttom no response)   sorry for my poor english

**Comment by jo3stevens** [comment]
Hey

stracker starts fine from the app in Windows though there is currently a UI bug where it doesn't show a started state even though it is running.

I have no idea for linux as I don't run any linux severs and the linux support was added by a contributor.

Cheers

**Comment by wuchyi** [comment]
Hey, sorry to bring up this old topic. 
I've realised the probably issue is that in server.js, the action to spawn the stracker server calls for stracker.exe, which obviously does not work on Linux. 

I've tried changing it to `/stracker_linux_x86/stracker `though but it doesn't work. 

edit:
#54 has an update to server.js
