### ISSUE TITLE
Missing Something to make it works

### ISSUE THREAD

**Issue by philmcphil** [jo3stevens/ACServerManager#11]
Hello and thank you for this very usefull tool....

My knowledges are very basics...I have this error message runing it on windows server:
C:\_ACServers\AC_Server_Manager_17>node server.js
C:\_ACServers\AC_Server_Manager_17\settings.js:2
  serverPath: 'C:\_ACServers\Server_17\',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
_SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\_ACServers\AC_Server_Manager_17\server.js:11:16)
    at Module._compile (module.js:570:32)_

C:\_ACServers\AC_Server_Manager_17>pause

Any help is welcome.
Regards.
Phil.

**Comment by icoicqico** [comment]
Have you got nodejs?

**Comment by philmcphil** [comment]
Hello, yes i´ve dowloaded it ....

**Comment by philmcphil** [comment]
Ans i run it on : windows standard_2012_r2 (64BITS)

**Comment by philmcphil** [comment]
The AC server root:
C:\_ACServers\Server_17

The AC Server Manager root:
C:\_ACServers\Server_17\AC_Server_Manager_17

The setting.js file:
module.exports = {
  serverPath: 'C:\_ACServers\Server_17\',
  contentPath: '',
  sTrackerPath: 'C:\_ACServers\Server_17\',
  username: 'xxxx',
  password: 'xxxxx',
  port: xxxx
};

The server.js file:
As default

**Comment by icoicqico** [comment]
Maybe try to add / after c: ?

**Comment by philmcphil** [comment]
Done...No changes...

**Comment by philmcphil** [comment]
@icoicqico do you have it working on your side ?
Are you using the STracker also ?
And  is there something to add or change in the servercfg.ini at the line:
UDP_PLUGIN_LOCAL_PORT=??
UDP_PLUGIN_ADDRESS=??
AUTH_PLUGIN_ADDRESS=??
LEGAL_TYRES=H;M;S
WELCOME_MESSAGE=

Should i put the open port value on one of this line

**Comment by icoicqico** [comment]
I am using Linux, but I had tried to start on windows before, and it works. plugin port is for plugin like stracker. And Stracker is another plugin, this manager doesn't include that, only help you to start it on the webpage. Have you installed the Stracker at the right location? If not set the path to '' and try again

**Comment by icoicqico** [comment]
If you have Stracker installed you have to set the plugin local port to 12000 and the plugin address to 127.0.0.1:11000

**Comment by philmcphil** [comment]
Thanks for your support...Yes i have STracker working fine....I asked about that just in case any of this line should receive the open port used for ACServermanager

In that case i´m OKAY so , i don´t know what am i missing....

**Comment by philmcphil** [comment]
There is no thread on the official AC forum ?

**Comment by icoicqico** [comment]
maybe I know, just tried to start on windows again, change \ to / of all path

**Comment by philmcphil** [comment]
God bless you ;)

One step complished ;)

The HTTP access works but the server still having error:
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
closing code: 2

**Comment by philmcphil** [comment]
Ok it works ;)

**Comment by philmcphil** [comment]
Thank you for your time ;)

**Comment by philmcphil** [comment]
Okay i still have few things missing with the acServerManager.bat .It does´nt load the content files at the good pointing root 

Why, certainly because i have 16 server running independently so , the bat file is at this root :"
C:\_ACServers\Server_05\AC_Server_Manager_05

And the fully game content folder is here :"
C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content

So do you know what do i need to change in the bat file:"
@echo off
cls
cd content/tracks
FOR /D %%G in (*) DO (
	echo Removing existing ui folder for %%G
	rmdir  "%~dp0server\content\tracks\%%G\ui\" /s /q
	echo Creating ui folder for %%G
	mkdir "%~dp0server\content\tracks\%%G\ui"
	echo Copying ui folder for %%G
	xcopy /s /e /y %%G\ui "%~dp0server\content\tracks\%%G\ui"
)
cd ../cars
FOR /D %%G in (*) DO (
	echo Removing skins folder for %%G
	rmdir  "%~dp0server\content\cars\%%G\skins\" /s /q
	echo Creating skins folder for %%G
	mkdir "%~dp0server\content\cars\%%G\skins"
	echo Copying skins directory structure for %%G
	xcopy /t /e /y %%G\skins "%~dp0server\content\cars\%%G\skins"

**Comment by ClarkParker** [comment]
First of all you have to create for each server the same folder structure as in the original AC folder.
In your example this should be:
C:_ACServers\Server_05\AC_Server_Manager_05\server\content\tracks
and
C:_ACServers\Server_05\AC_Server_Manager_05\server\content\cars

The batchfile should be edited like this:

@echo off
cls
cd \
cd "C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content\tracks"
FOR /D %%G in () DO (
echo Removing existing ui folder for %%G
rmdir "%~dp0server\content\tracks%%G\ui" /s /q
echo Creating ui folder for %%G
mkdir "%~dp0server\content\tracks%%G\ui"
echo Copying ui folder for %%G
xcopy /s /e /y %%G\ui "%~dp0server\content\tracks%%G\ui"
)
cd \
cd "C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content\cars"
FOR /D %%G in () DO (
echo Removing skins folder for %%G
rmdir "%~dp0server\content\cars%%G\skins" /s /q
echo Creating skins folder for %%G
mkdir "%~dp0server\content\cars%%G\skins"
echo Copying skins directory structure for %%G
xcopy /t /e /y %%G\skins "%~dp0server\content\cars%%G\skins"
pause

a tip:
If you'll use the same content on every server I'd use only **one** "server\content" place - so you needn't to copy the content to every of your 16 servers.
You just need to put the same content path in every settings.js (contentPath: '',)

Perhaps you should make a Backup before you test that! ; )
