### ISSUE TITLE
Still working on the current builds?

### ISSUE THREAD

**Issue by cazzoo** [jo3stevens/ACServerManager#12]
Hi there,

This tool look promising but I just wonder if it still work with the lastest game update.
I currently look for a solution for mates (not using it myself) and this would be really nice to give them this server manager panel.

Thanks for your reply.
Regards

**Comment by ClarkParker** [comment]
Hi,
in my case the Web-interface still works with the last Assetto build, but there are (now or better since view AC updates) some problems and issues you have to know. So the sTracker for example will load for ever on the Web Gui - but internal it works. There also some refresh issues with the "server configuration" section as well. Often the fields are empty and you have to refresh the site several times. Also changing tracks is most of the time little bit tricky because the server manager doesn't or can't load the Track ui data proper. Some options and functions from the original Assetto Server tool are missing as well.
Unfortunate jo3stevens (the developer) has quit this project in my opinion; no update for over one year now.
Really sad... this project was very very useful and there isn't any alternative tool.... so jo3stevens, if you read this... pls come back to us! ; )

**Comment by ClarkParker** [comment]
There is also a new branch of ACServerManager:
https://github.com/Pringlez/ACServerManager

**Comment by philmcphil** [comment]
Does anyone could give me a hand on this.HTML and config works but when loading i have this:


C:\_ACServers\Server_17\AC_Server_Manager_17>node server.js
OS is win32
Starting Windows Server
Server CFG Path :  cfg/server_cfg.ini
Entry List Path :  cfg/entry_list.ini
Assetto Corsa Dedicated Server v1.9
Protocol version: 190

2017-01-24 20:53:57.4107488 +0100 CET
Num CPU: 8

C:\_ACServers\Server_17\AC_Server_Manager_17\server.js:66
                        throw (err);
                        ^

Error: ENOENT: no such file or directory, open 'C:\_ACServers\Server_17\AC_Serve
r_Manager_17\logs\server_20170024_205357_log.txt'
    at Error (native)

C:\_ACServers\Server_17\AC_Server_Manager_17>pause
Appuyez sur une touche pour continuer...

**Comment by Pringlez** [comment]
It's trying to open the log file to write stuff, but can't find it.
Your directory structure looks strange...
It begins with "C:_ACServers\" - which looks wrong, it should be "C:\_ACServers\"
The back slash is missing for some reason...

Whats in your settings.js file?

**Comment by ClarkParker** [comment]
Is ther a "log" folder under "C:_ACServers\Server_17\AC_Serve
r_Manager_17\" ?
If not... create one

**Comment by philmcphil** [comment]
Thanks for you help,,,,,Here it is 
![acserver](https://cloud.githubusercontent.com/assets/8143769/22274459/f284c312-e2a6-11e6-8695-9c92c304f361.JPG)

**Comment by philmcphil** [comment]
module.exports = {
  serverPath: 'C:/_ACServers/Server_17/',
  contentPath: 'C:/_ACServers/Server_17/',
  sTrackerPath: 'C:/_ACServers/Server_17/',
  username: '',
  password: '',
  port: xxxx
};

**Comment by ClarkParker** [comment]
ok... there is no "log" folder...
Anyway, your "settings.js" has also wrong path in it. In the folder "C:/_ACServers/Server_17/" is neither a "content" folder nor the "sTracker" and also no "server" folder but in your settings.js this path are set?!?! Why? This can never ever work!
First solution: Point in the "settings.js" to right folder
Second solution: Copy the respective folder to your "C:/_ACServers/Server_17/" path
(Third unconventional solution: make symlinks to the folder - but this is more for pro users)

But in my opinion first of all you should learn how to use this by installing one server instance and one frontend... not 17... to do so please read this and follow the install instructions step by step:
https://github.com/Pringlez/ACServerManager/blob/master/README.md
After that we can talk about installing more than one Server ;)

If you need help to install ONE server feel free to ask for help (after reading the instructions) :)

**Comment by philmcphil** [comment]
@ClarkParker 

Thanks for your time......This is my server number 17 ......The ACMANAGER is only used for this one.....Before the update , everything was working perfectly...Even now the HTML connection work, server setting page works...The only thing that doesn´t work is when pressed "run" ...i HAVE THIS ERROR....

**Comment by Pringlez** [comment]
Backup your server config, entry list and download a new copy from my fork. Copy over your config, entry list & run npm install to download the dependencies. Point your serverPath to your assetto game server & don't set the content path! 🥇 :)
Make sure you open the ports required, sometimes the ac server will fail to start if the right ports are not open in your firewall / router etc.

**Comment by Pringlez** [comment]
I've notice some issues with saving server configurations with my version of acmanager, can anyone else confirm issues with saving configs & entry lists?
It seems to cut out some of the text coming back from the server config file. Maybe it's just an issue on Linux?

**Comment by philmcphil** [comment]
@Pringlez , i´m back...I check that and let you know....

**Comment by Cele91** [comment]
@Pringlez I have this problem on Windows

**Comment by jo3stevens** [comment]
Sorry I haven't been active on the project since my last kid took away all my free time! Just seen this flurry of activity. I still use the app on my server but it is missing a lot of features and settings in recent builds. I've been planning to get it all updated soon.

**Comment by cazzoo** [comment]
Looks sexy now, I'll check that ASAP.
Also, I'll try to set this environment as Docker env to see if it'd work as is. Anybody has already did that so far?
