### ISSUE TITLE
Still no access

### ISSUE THREAD

**Issue by JakubDvonc** [jo3stevens/ACServerManager#16]
Hello, as I am starting to be a little desperate, I would like to ask for help. I am still not able to connetct to IP, where the Assetto manager is installed and running.

What I did:
1) instal EC2 server on Amazon, with Amazon linux. On a security groups I set all port AC needs HTTP 80, SSH 22, UDP 9600, TCP 8081, TCP 50041 a 2, TCP 42820
2) Install NVM, Node, MP2 and ACmanager
3) set the settings.js to: 
 serverPath: 'home/ec2-user/server/',
  contentPath: 'home/ec2-user/server/content/',
  sTrackerPath: '',                                                        
  port: 42820            
4)with "netstat -tanp | grep LISTEN":
tcp        0      0 0.0.0.0:42820               0.0.0.0:*                   LISTEN      -                                                                       
tcp        0      0 0.0.0.0:111                 0.0.0.0:*                   LISTEN      -                                                                       
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      -                                                                       
tcp        0      0 :::111                      :::*                        LISTEN      -                                                                       
tcp        0      0 :::49141                    :::*                        LISTEN      -                                                                       
tcp        0      0 :::22                       :::*                        LISTEN      -                                                      

5)with "sudo iptables -L":
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:42820
6) ACmanager is running

and nothing, the IP is not accesable at all. Could please someone tell me what I am doing wrong?
As I do not understand linux at all I am noob on this, but I hope I did everythnig from the manual.

Confusing for me is:
1) 'home/ec2-user/server/' in settings.js is this correct way for amazon EC2 linux ?
2) I put to the home/ec2-user/server/ whole SERVER folder from game, but....the game is for windows and this is linux? isnt it wrong?

Thank you very much.

Jakub

**Comment by JakubDvonc** [comment]
ok, I just start the instalation over again and it works now. Dont know why.

**Comment by JakubDvonc** [comment]
But I didnt move much farther.

1) Passwords:
 username: '',
  password: '',
If I let it empty, I am able to connect to the IP and port.
If I put anything like:
 username: 'a',
  password: 'a',
there is no way, how to connect. It only shows the login. But the username and password doesnt work at all. 
But ok, I let it empty and login.

2)
 serverPath: '..//',
 contentPath: '..//',

my direcotry structure is this: /home/ec2-user/server/ for acServer,exe
and /home/ec2-user/server/content/ for content

I tried all possibilities, but only one work:
serverPath: '../server/',
contentPath: '../server/content/',
have no idea why this one, but with this setting I can see tracks and cars from Content.

BUT STILL NO ABLE TO START THE SERVER. The "start" button just doesnt do anything.
I hope I have set and open all ports.

Please help. Thank you.

**Comment by Pringlez** [comment]
There is an issue with the authentication, I believe surtic86 was working on a fix here - https://github.com/Pringlez/ACServerManager/pull/2

I would't suggest using the authentication feature right now until it's fixed, leave the username & password blank. 

As for your issue with starting the server make sure you point the 'serverPath' variable to your assetto corsa server directory. You said your directory structure is : '/home/ec2-user/server/ for acServer,exe' ??

Well if that's your assetto corsa server directory then set the 'serverPath' to '/home/ec2-user/server/'

Where did you install the ac manager?

**Comment by JakubDvonc** [comment]
Hello,
first, thank you VERY MUCH for your help.

The authentication issue do not bother me, so I dont mind use it without password.

But the server path:

a) I set the server path to '/home/ec2-user/server/' but there is no difference. Still can connect to IP, but not able to Start the server.

b)my file structure for acmanager

/home/ec2-user/acmanager

see the picture:
![image](https://cloud.githubusercontent.com/assets/26374728/24247165/e11e0e84-0fca-11e7-8048-9bb6de05dc75.png)

**Comment by Pringlez** [comment]
Ok shutdown your ac manager instance, now start ac manager without using pm2...

With 'node server.js' in ac manager directory, goto ac manager in the browser and try to start the server again. Give us any error output from the running node application in the terminal.

**Comment by JakubDvonc** [comment]
I tried it - and it just did nothhing. Like nothing:

![image](https://cloud.githubusercontent.com/assets/26374728/24255648/5c384920-0fe6-11e7-8db5-f2f4b7d84663.png)

**Comment by JakubDvonc** [comment]
and another error when I click "Configuration"

Error - Error: ENOENT: no such file or directory, scandir '/home/ec2-user/server/content/tracks/drift/ui'
Error - Error: ENOENT: no such file or directory, scandir '/home/ec2-user/server/content/tracks/imola/ui'
Error - Error: ENOENT: no such file or directory, scandir '/home/ec2-user/server/content/tracks/ks_barcelona/ui'

and so on...

but this is stragne, when I look at my game dir: server/content/tracks/imola there is no "ui" folder too. So it is obvious, that the folder can not be either at the linux server.

**Comment by Pringlez** [comment]
That error your getting 'Error POST/api/acserver - Error: spawn EACCES'

I believe that is an permissions issue, you need to have the execution rights to basically spawn or create a new running process.

Go to your ac server directory and run 'ls -la' to see if you have the correct permissions to start the server.

Run something like: 'sudo chmod -R a+rwx /home/ec2-user/server' - to gain execution permissions on the server directory.

**Comment by JakubDvonc** [comment]
ok :) so now it looks like this:

OS is linux
Starting Linux Server
Server CFG Path :  cfg/server_cfg.ini
Entry List Path :  cfg/entry_list.ini
Assetto Corsa Dedicated Server v1.12.1
Protocol version: 200
2017-03-24 03:19:07.961910554 -0400 EDT
Num CPU: 1

LOCAL IP 0: 172.31.29.237
Using cfg path:  cfg/server_cfg.ini
Car list:
_ferrari_458_gt2_
Client interval HZ: 18
WARNING: RESULT_SCREEN_TIME was less of 30secs or not found, setting to default: 10secs
WARNING: MAX_CONTACTS_PER_KM was 0 or not found, setting to default: 5
AUTH_PLUGIN_ADDRESS 
TRACK=imola
CARS=["ferrari_458_gt2"]
Loading PRACTICE session
SESSION: Practice
TYPE=PRACTICE
TIME=10
LAPS=0
OPEN=1
WAIT TIME=0

Loading QUALIFY session
SESSION: Qualify
TYPE=QUALIFY
TIME=10
LAPS=0
OPEN=1
WAIT TIME=0

SESSION: Race
TYPE=RACE
TIME=0
LAPS=7
OPEN=1
WAIT TIME=60

DynamicTrack: first session, resetting grip
Trying to load DRS zones from: content/tracks/imola/data/drs_zones.ini

Loading ZONE_0 {0.901 0.116}

stderr: panic: invalid argument to Intn

goroutine 1 [running]:
math/rand.(*Rand).Intn(0x187142e0, 0x0, 0x187ae5f0)
        c:/go/src/math/rand/rand.go:141 +0xa3
math/rand.Intn(0x0, 0x7)
        c:/go/src/math/rand/rand.go:276 +0x2b
main.UpdateWeather()
        D:/dev/kunosprivate/go/src/acServer/weather.go:43 +0x27
main.initServerCfg()
        D:/dev/kunosprivate/go/src/acServer/ac_server.go:1470 +0x195a
main.main()
        D:/dev/kunosprivate/go/src/acServer/ac_server.go:260 +0x6e6

exit code: 2
closing code: 2

**Comment by JakubDvonc** [comment]
And this is the 'ls -la' command: 

[ec2-user@ip-172-31-29-237 acmanager]$ ls -la
total 76
drwxrwxr-x.  5 ec2-user ec2-user   194 Mar 23 16:02 .
drwx------.  9 ec2-user ec2-user   174 Mar 23 15:31 ..
-rw-rw-r--.  1 ec2-user ec2-user   631 Mar 13 18:22 acServerManager.bat
drwxrwxr-x.  8 ec2-user ec2-user   172 Mar 13 18:22 frontend
drwxrwxr-x.  2 ec2-user ec2-user  8192 Mar 24 05:29 logs
drwxrwxr-x. 60 ec2-user ec2-user  4096 Mar 17 11:32 node_modules
-rw-rw-r--.  1 ec2-user ec2-user   430 Mar 13 18:22 package.json
-rw-rw-r--.  1 ec2-user ec2-user  5539 Mar 13 18:22 README_Linux.md
-rw-rw-r--.  1 ec2-user ec2-user  5253 Mar 13 18:22 README.md
-rw-rw-r--.  1 ec2-user ec2-user 26724 Mar 13 18:22 server.js
-rw-rw-r--.  1 ec2-user ec2-user   183 Mar 23 16:02 settings.js
-rw-rw-r--.  1 ec2-user ec2-user    20 Mar 13 18:22 start.bat
[ec2-user@ip-172-31-29-237 acmanager]$

**Comment by Pringlez** [comment]
Run that command in your ac server directory.

I'm not sure whats going with that new error your getting...
What Linux distro are you running?

I'm running a server just fine 12.04 Ubuntu.

**Comment by JakubDvonc** [comment]
Red Hat Enterprise Linux 7.3 (HVM), 

But never mind, I try the installation again and I will try to use Ubuntu. Than let you know.

Thank you again for now.....

**Comment by JakubDvonc** [comment]
Wow !!!!!! I see it running !!!

T.H.A.N.K YOUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU

**Comment by Pringlez** [comment]
Cool, :1st_place_medal: 

Seems to be an issue with amazon's cloud based distro...

**Comment by JakubDvonc** [comment]
OK, so here again :(
Everything is fine, server works, I can set everything and I can see the server in AC game server list, but if I try to open it on AC it says: "Unable to contact server"

So again ask for help :( sorry

**Comment by Pringlez** [comment]
Double check all your firewall settings.

Make sure to open TCP 9600, UDP 9600, TCP 8081 if you haven't changed the default ports for the ac server

Maybe just disable your firewall / iptables to see if it works...

**Comment by JakubDvonc** [comment]
diabling firewall make it :)
Thanks again.

Jakub

**Comment by JakubDvonc** [comment]
So I think I am going totaly mad out of this :)
After everything works and I can finally join the server, this appears:

"Error: Server is running different protocol"
:(

**Comment by JakubDvonc** [comment]
When you receive an error such as "WARNING: requested to join with a different protocol (Client=160 , Server=150)"
Then this means that the server is not running on the same version as your client. To resolve the problem simply click the steam update button in the control panel.

have to try this....

**Comment by Pringlez** [comment]
The ac server needs to be updated, just run the same command used to install the server.

**Comment by JakubDvonc** [comment]
Everything is fine now.
Thank you again.

**Comment by JakubDvonc** [comment]
OK, maybe one last question (sorry about that)
If I am in the game and to the chat I write: /admin than the response is: "Command refused"
terminal (node server.js) says: you are not admin of the server
Can I fix this?
