### ISSUE TITLE
Restart button not work

### ISSUE THREAD

**Issue by Cele91** [jo3stevens/ACServerManager#18]
If you click, he stops the server and the cmd creates this error
```
Error listening %!e(syscall.Errno=536870951)
DynamicTrack: first session, resetting grip
Error listening %!e(syscall.Errno=536870951)
Weather update. Ambient: 19.150816 Road: 28.775797 Graphics: 3_clear
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
No laptime available, use car index for grids
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
POS: 1, SessionID:0
POS: 2, SessionID:1
POS: 3, SessionID:2
POS: 4, SessionID:3
POS: 5, SessionID:4
POS: 6, SessionID:5
POS: 7, SessionID:6
POS: 8, SessionID:7
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
POS: 9, SessionID:8
POS: 10, SessionID:9
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
POS: 11, SessionID:10
POS: 12, SessionID:11
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
POS: 13, SessionID:12
POS: 14, SessionID:13
POS: 15, SessionID:14
POS: 16, SessionID:15
Error listening %!e(syscall.Errno=536870951)
POS: 17, SessionID:16
POS: 18, SessionID:17
POS: 19, SessionID:18
POS: 20, SessionID:19
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
SENDING session name : Practice
SENDING session index : 0
Error listening %!e(syscall.Errno=536870951)
SENDING session type : 1
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
SENDING session time : 480
SENDING session laps : 0
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Server started
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)

stderr: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4e19ed]

goroutine 18 [running]:
net.(*UDPConn).ReadFromUDP(0x0, 0x1265e800, 0x800, 0x800, 0x862f1dd8, 0x0, 0x232
4bb0, 0x0)
        c:/go/src/net/udpsock.go:94 +0x1d
ksnet.(*UDPSocket).ReceivePacket(0x12646be0, 0x0)
        D:/dev/kunosprivate/go/src/ksnet/udp_socket.go:99 +0x68
main.ReceiveRun(0x12668000)
        D:/dev/kunosprivate/go/src/acServer/ac_server.go:317 +0x23
created by main.RunServer
        D:/dev/kunosprivate/go/src/acServer/ac_server.go:473 +0x7d

Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)
Error listening %!e(syscall.Errno=536870951)

exit code: 2
closing code: 2
exit code: 1
closing code: 1

```

**Comment by Pringlez** [comment]
Running on Windows? I haven't fully tested the application on Windows yet, the feature seems to work just fine on Linux although.

**Comment by Cele91** [comment]
Windows yes :o

**Comment by jo3stevens** [comment]
Hey @Cele91 

I'm not having this on my windows server. Does it prevent you from starting the server again?

Cheers

**Comment by Cele91** [comment]
Click 'Stop' and then 'Start' and the server starts, but the problem remains with 'Restart' button :) . I use the latest version revisited of acmanager

**Comment by jo3stevens** [comment]
Thanks @Cele91 . Restart button was added by @Pringlez so I'll check it for Windows.

**Comment by Cele91** [comment]
@jo3stevens Thanks a lot :D

**Comment by Pringlez** [comment]
I'm not really sure if I implemented that feature correctly or not :face_with_head_bandage: 

It seems to work fine in Linux @jo3stevens

**Comment by jo3stevens** [comment]
Had a quick look at implementation @Pringlez but haven't tried on my server yet. Creating a restart function in server.js was unnecessary. We already have a working stop and start methods, so the restart button should have just been UI functionality that called stop, then called start. Not much point having duplicated code in a single method.

**Comment by jo3stevens** [comment]
Hey @Cele91 

Are you accessing the web app on a browser directly on your server when this happens?

I just did some refactoring so that the web app uses the existing start and stop methods and this is working fine for restarting when using a browser session on my local machine, yet if I use a browser on the actual server I get that error. Quite strange...

**Comment by Cele91** [comment]
@jo3stevens 
I never tried the restart button directly from the browser of my dedicated server. I only tried using Chrome from my pc

**Comment by jo3stevens** [comment]
Thanks @Cele91 

I'm thinking it's just a timing thing; it's probably trying to start the server up again before its properly shut it down. I'll try a timeout or find a more definitive way to ensure the server it stopped.

Cheers

**Comment by Cele91** [comment]
Perfect :) thank you very much @jo3stevens

**Comment by jo3stevens** [comment]
I put a small delay between the start and stop when resetting and that seems to have fixed the problem.

Cheers

**Comment by Cele91** [comment]
@jo3stevens  I have a doubt. I click 'Start' of server (and server start),after I click 'Start' of sTracker (and sTracker start). But if I have both started and I click 'Restart' of server, sTracker remains started but does not restart with the server. Is correct that?

**Comment by jo3stevens** [comment]
Yeah that was the intention @Cele91 

From my understanding with stracker running as a UDP plugin it doesnt have a direct dependency on on acserver. It should be possible to restart acserver and leave stracker running and acserver will hook up to it on start.

Let me know if that's not the case and you're having an issue. I also intend to remove the logic that stops stracker when you stop acserver.
