### ISSUE TITLE
AC Manager does not save some values

### ISSUE THREAD

**Issue by Cele91** [jo3stevens/ACServerManager#22]
I noticed that the panel does not save some things. After setting several things, click save and in the cfg I always find values not changed
(Win server 2008)

**Comment by jo3stevens** [comment]
Hey @Cele91 

Can you tell we which settings you are finding this with. The app is quite out of date for all of the new settings which I plan to update soon.

Cheers

**Comment by Cele91** [comment]
The sessions if are 'on' or 'off'; The various sessions settings; The options with checkbox;

**Comment by jo3stevens** [comment]
Hey @Cele91 

Yep it's those checkboxes added by @Pringlez. They don't work correctly at all with angular. I'll look for an alternative.

Cheers

**Comment by jo3stevens** [comment]
I've replaced the checkboxes with the latest bootstrap switch plugin, but there is still an intermittent saving issue on several pages. When it happens I'm seeing a JS error in the console so will need to investigate. I'm thinking it's to do with the new fields added.

**Comment by jo3stevens** [comment]
I believe this is now fixed. There were a few issues, one being the checkboxes not binding properly, some numeric input fields not using the string-to-number directive and also the validation directive placed on the wrong element in a few places.

I've tided this all up and it seems to be saving correctly now.
