### ISSUE TITLE
Help page background page blank

### ISSUE THREAD

**Issue by Cele91** [jo3stevens/ACServerManager#29]
I do not see the background for the help page. I also tried to create a new re assigning it with the new name but still does not see.

**Comment by jo3stevens** [comment]
@Cele91 

Unsure what you mean by background page? I've noticed that the menu button does nothing when scaled down to mobile; is that what you're referring to?

**Comment by Cele91** [comment]
The red left column does not have the background in Help page
http://i.xomf.com/ffmkp.png

**Comment by jo3stevens** [comment]
Ah okay. Those backgrounds where added by @Pringlez  and I think @surtic86 created the help page. It's not really an issue. The menu not working when scaled down to mobile is though.

**Comment by Pringlez** [comment]
I'll look into the issue @Cele91 , I think it's only small problem.

**Comment by Pringlez** [comment]
@Cele91 The fix is in the latest pull request, enjoy!
