### ISSUE TITLE
Problem with old server_cfg on multiple server

### ISSUE THREAD

**Issue by Cele91** [jo3stevens/ACServerManager#34]
I'm noticing problems on multiple servers. I have some servers with the new panel, and some with the old panel. If I try to install the new panel on a server that had the old panel, the new panel starts giving problems, such as the time appears and the field is empty (hh, mm) and if I try to do "Save "it does not appear green "Save" confirmation. But if I take a new cfg last release of Assetto Corsa, everything goes back to work. Everything breaks down again if I change the UDP / TCP or sTracker in cfg. Solutions?

**Comment by Pringlez** [comment]
You shouldn't really use the old cfg with new panel, the developers of AC have released number updates on the server-side that are not completely compatible with the old cfg.

Migrate your old cfg's to the new version
