### ISSUE TITLE
File Path

### ISSUE THREAD

**Issue by KaiseR877** [jo3stevens/ACServerManager#35]
Hi 
I've some problemes, this is my setting.jr

module.exports = {
  serverPath: 'C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Dedicated Server\', 
  contentPath: 'C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Dedicated Server\content\',
  sTrackerPath: '',
  username: '',
  password: '',
  port: 3000
};

And server manager dont run! But path is correct! This is warning

C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Dedicated Server\acmanager>node server.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'basic-auth-connect'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Dedicated Server\acmanager\server.js:7:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Dedicated Server\acmanager>pause
Premere un tasto per continuare . . .

My server path is C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Dedicated Server
And content is C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Dedicated Server\content

Where am I wrong?
Ty for patience

**Comment by Cele91** [comment]
IT: Apri 'cmd.exe' e digita 'cd C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Dedicated Server\acmanager' , poi 'npm install' e poi prova ad avviarlo di nuovo

EN: Open 'cmd.exe' and type 'cd C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Dedicated Server\acmanager' , and type 'npm install' . After this re lauch the .bat file

**Comment by KaiseR877** [comment]
IT: Cavolo, ho solamente aggiornato i file, non mi ricordavo quel passaggio! Grazie mille!!!

ENG: Dam, i just update the file, i forgot this point. Thanks a lot!!!
