### ISSUE TITLE
can't get it to run

### ISSUE THREAD

**Issue by SpyBot68** [jo3stevens/ACServerManager#48]
![image](https://user-images.githubusercontent.com/39316815/40091391-49ee7594-5885-11e8-98b1-4387a2591344.png)

so i have nodejs and everything else set but i seem to be getting this error, im assuming this is something simple but i cant figure it out, have been trying all day

**Comment by Pringlez** [comment]
Did you run 'npm install' in the directory first?

**Comment by SpyBot68** [comment]
i had but just incase i redid it and now im getting a different error
![image](https://user-images.githubusercontent.com/39316815/40188524-21319728-59c8-11e8-8836-226b16dda5cc.png)
![image](https://user-images.githubusercontent.com/39316815/40188545-2ddf3282-59c8-11e8-8058-dc1a283f2894.png)

**Comment by SpyBot68** [comment]
![image](https://user-images.githubusercontent.com/39316815/40211703-1c3c5508-5a1a-11e8-88ba-35bcb93aca99.png)
 so fixed the last issue but now i have this one.... firewall disabled and UDP and TCP port open ....

**Comment by SpyBot68** [comment]
had to change the port to 4 digits 

thx for the fast answer though
