### ISSUE TITLE
STracker not working any longer

### ISSUE THREAD

**Issue by ClarkParker** [jo3stevens/ACServerManager#5]
Hi Joe,
yes, it's me again. :)

I updated STracker to the latest version and now it won't start any longer. In the readme of STracker you can find following note:

---

Since version 3.0.0 the AC server has to be configured for plugin usage in server_cfg.ini:

[SERVER]
UDP_PLUGIN_LOCAL_PORT=11000
UDP_PLUGIN_ADDRESS=127.0.0.1:12000 

---

So... did I miss something? Is it possible that ACServerManager writes this settings into the server_cfg.ini?

Thanks in advance

Cheers
Flo

**Comment by ClarkParker** [comment]
OK... get it...
I saw in your server.js that you "only" parse the server_cfg.ini and by changing settings your function saveConfig only writes the specific parameter in the .ini file. I thought you replace the whole server_cfg.ini
______________
So everybody which has the same Problem after updating STracker to 3.0 or above ... this solution should work:

1) Navigate in your File explorer to the server path you've set in the ACServerManager settings.js for "serverPath".
        For Example in my Case "d:/Games/SteamLibrary/steamapps/common/assettocorsa/server/"
2) Go in subfolder "cfg"
3) Open the File "server_cfg.ini" with an editor an change the values of the following lines like this:
UDP_PLUGIN_LOCAL_PORT=11000
UDP_PLUGIN_ADDRESS=127.0.0.1:12000 
4) Save file
Done... restart the Server and STracker
In my testing these lines keep stored when you change settings (Tracks,cars,what ever) with ACServerManager.
Note:
This works only if you run one instance of ACServer and one instance of STracker
If you want to run more instances please read the "readme.txt" of STracker
________________
@Joe
Perhaps you can look at this a little bit closer, there is a lot of new stuff in the STracker config ;)

Cheers
Flo

PS.: Once again... thanks for your good work Joe, we use your tool a LOT!!!! :)

**Comment by jo3stevens** [comment]
Hey Clark

Sorry totally missed this as I didn't get any notification, weird..

Thanks for the info, I haven't tried the latest sTracker, but if there is ever an AC update that adds things to the server_cfg.ini it's worth updating the file on the server. The app will read in the entire config and replace values, so like you say they won't get overwritten. That said, those are setting I should add to the web app.

Multiple instance is something that's been brought up before, as is presets and few other things. All things I will get around to at some stage :)

Cheers
Joe

**Comment by ClarkParker** [comment]
Hey Joe (where you goin' with that gun in your hand?) ; )
No Problem...
I saw you've already implemented the UDP Plugin fields to the front end; perfect; as always! :)
Very good job Joe and thanks!
I think this "issue" can be closed now.

Cheers 
Flo

PS.: Can't wait to see Multiple instance in the further updates! ; )
