### ISSUE TITLE
Tracks with multiple layouts not selectable in the gui (and then some)?

### ISSUE THREAD

**Issue by olliraa** [jo3stevens/ACServerManager#6]
Something weird happening here... Done the installation exactly as told, but the tracks with multiple layouts only appear as one in the drop down menu. Also it seems (have to test some more) that the server config is not saved after all?!

Is this a known problem?

Also one feature request. Please add a button "update car to all the players in the entry list." We have a closed league, so that would be really handy :)

Thanks!

**Comment by jo3stevens** [comment]
This sounds like the app wasn't configured correctly though there is an issue if adding mod layouts to a track with just a single layout.
