### ISSUE TITLE
sTracker infinite loading

### ISSUE THREAD

**Issue by Cele91** [jo3stevens/ACServerManager#7]
Tracker 3.1.7 continues to load endless

**Comment by ClarkParker** [comment]
Same here, but this seems to be "just a gui problem". In my Case sTracker works anyway.

**Comment by jo3stevens** [comment]
@Cele91 

Looks like you raised this twice but yes it's just a front end issue due to a change to stracker. I'll get it fixed soon.

Cheers

**Comment by jo3stevens** [comment]
Dupe
