### ISSUE TITLE
not working on linux?

### ISSUE THREAD

**Issue by icoicqico** [jo3stevens/ACServerManager#9]
I have downloaded this program, and when I start the start.sh, then no response it is just version problem or sth?

**Comment by icoicqico** [comment]
I mean nothing loading @linux cmd and stuck there

**Comment by p3t3c** [comment]
Assuming you have node js installed. You can try running the command from the command line and confirming that it starts.

**Comment by icoicqico** [comment]
I have node js, before I installed node.js it show me an error msg. After I install it, told me the game server directory is wrong, after I set it correctly, then no response.

**Comment by icoicqico** [comment]
![image](https://cloud.githubusercontent.com/assets/24432546/20967878/6a9ffc92-bcbc-11e6-9d6c-8dcad6b49bed.png)
that problem fixed, but can anyone tell me how to fix this? thanks

**Comment by p3t3c** [comment]
Have you modified settings.js to suit your system?

**Comment by p3t3c** [comment]
Ahh you need to change it to point to your executables

**Comment by icoicqico** [comment]
yes, and the web page is working now, can change setting on the website but cant start server on it

**Comment by p3t3c** [comment]
Does the acserver run on your system if you start by hand?

**Comment by icoicqico** [comment]
yes if start by hand it is work

**Comment by icoicqico** [comment]
it is working, i'm stupid because the server is running by hand, so cant be started on webpage.

**Comment by icoicqico** [comment]
May I ask another question? If I want to use stracker in linux server, the sTracker link should be .../Stracker or .../Stracker/Stracker_linux_x86 ?
